DROP VIEW IF EXISTS DEMOS.PUBLIC.AIR_QUALITY_FILTERED;
CREATE VIEW IF NOT EXISTS DEMOS.PUBLIC.AIR_QUALITY_FILTERED AS 
SELECT
    CAST(LATITUDE AS NUMBER) AS LATITUDE,
    CAST(LONGITUDE AS NUMBER) AS LONGITUDE,
    PARAMETERNAME,
    CAST("YEAR" AS NUMBER) AS "YEAR",
    CAST(ARITHMETICMEAN AS NUMBER) AS ARITHMETICMEAN,
    CAST("90THPERCENTILE" AS NUMBER) AS "90THPERCENTILE",
    CAST("50THPERCENTILE" AS NUMBER) AS "50THPERCENTILE",
    CAST("10THPERCENTILE" AS NUMBER) AS "10THPERCENTILE",
    ADDRESS,
    STATENAME,
    COUNTYNAME,
    CITYNAME
FROM 
    AIR_QUALITY_DATA_UNITED_STATES.PUBLIC.AIR_QUALITY 
WHERE
    SAMPLEDURATION = '24 HOUR' AND
    METRICUSED = 'Observed Values' AND
    PARAMETERNAME IN (
    'Suspended particulate (TSP)',
    'Lead (TSP) STP',
    'Chromium (TSP) STP',
    'Sulfate (TSP) STP',
    'Arsenic (TSP) STP',
    'Cadmium (TSP) STP',
    'Manganese (TSP) STP',
    'PM10 - LC',
    'Nickel (TSP) STP',
    'Iron (TSP) STP',
    'Zinc (TSP) STP',
    'Copper (TSP) STP',
    'Cobalt (TSP) STP',
    'Vanadium (TSP) STP',
    'Barium (TSP) STP',
    'Beryllium (TSP) STP',
    'Nitrate (TSP) STP',
    'Benzene',
    'Molybdenum (TSP) STP',
    'Toluene',
    'Sample Max Baro Pressure',
    'Sample Min Baro Pressure',
    'Average Ambient Pressure',
    'Average Ambient Temperature',
    'Ambient Min Temperature',
    'Ambient Max Temperature',
    'Sample Flow Rate- CV',
    'Sample Volume',
    'Elapsed Sample Time',
    'Ethylbenzene',
    'Dichloromethane',
    'Carbon tetrachloride',
    'Methyl chloroform',
    'Tetrachloroethylene',
    'Chloroform',
    'Sulfate PM10 STP',
    'Trichloroethylene',
    'o-Xylene',
    'm/p Xylene',
    'Ethylene dichloride',
    'Styrene',
    'Nitrate PM10 STP',
    'Vinyl chloride',
    '1,3-Butadiene',
    'Chlorobenzene',
    'Sulfur dioxide',
    '1,4-Dichlorobenzene',
    '1,2-Dichlorobenzene',
    '1,2-Dichloropropane',
    '1,1,2-Trichloroethane',
    'Bromomethane',
    'Chloride PM10 STP',
    'n-Octane',
    '1,1-Dichloroethane',
    '1,3,5-Trimethylbenzene',
    '1,2,4-Trimethylbenzene',
    '1,3-Dichlorobenzene',
    'Propylene'
    );

